# -*- coding: utf-8 -*-
"""task3_analysis.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10GR_IMDJ4q83zVC2XHGI8RejUVf9gH0z
"""

from google.colab import drive
drive.mount('/content/drive')

os.makedirs("data", exist_ok=True)

# task1_data_collection
import requests
import time
import json
import os          # to interact with the operating system — such as working with files, directories, environmen
import re          # Ex for re:Search the string to see if it starts with "The" and ends with "Spain"
from datetime import datetime

# --- Configuration ---
TOP_STORIES_URL = "https://hacker-news.firebaseio.com/v0/topstories.json"
ITEM_URL_TEMPLATE = "https://hacker-news.firebaseio.com/v0/item/{}.json"
HEADERS = {"User-Agent": "TrendPulse/1.0"}

CATEGORIES = {
    "technology": ["ai", "software", "tech", "code", "computer", "data", "cloud", "api", "gpu", "llm"],
    "worldnews": ["war", "government", "country", "president", "election", "climate", "attack", "global"],
    "sports": ["nfl", "nba", "fifa", "sport", "game", "team", "player", "league", "championship"],
    "science": ["research", "study", "space", "physics", "biology", "discovery", "nasa", "genome"],
    "entertainment": ["movie", "film", "music", "netflix", "game", "book", "show", "award", "streaming"]
}

def fetch_and_process_stories():
    print("Fetching top story IDs...")
    try:
        response = requests.get(TOP_STORIES_URL, headers=HEADERS)
        response.raise_for_status()
        story_ids = response.json()
    except requests.exceptions.RequestException as e:
        print(f"Failed to fetch top stories: {e}")
        return []

    collected_stories = []

    for category, keywords in CATEGORIES.items():
        print(f"\n--- Hunting for 35 stories in: {category.upper()} ---")
        category_count = 0

        for story_id in story_ids:
            if category_count >= 35:
                break

            # Skip if we already grabbed this story
            if any(s.get("post_id") == story_id for s in collected_stories):
                continue

            try:
                item_url = ITEM_URL_TEMPLATE.format(story_id)
                item_response = requests.get(item_url, headers=HEADERS)
                item_response.raise_for_status()
                story_data = item_response.json()

                if story_data and "title" in story_data:
                    title_lower = story_data["title"].lower()

                    match_found = False
                    for keyword in keywords:
                        if re.search(rf"\b{re.escape(keyword)}\b", title_lower):
                            match_found = True
                            break


# TASK 2: Extract the Fields
                    if match_found:
                        processed_story = {
                            "post_id": story_data.get("id"),
                            "title": story_data.get("title"),
                            "category": category,
                            "score": story_data.get("score", 0),
                            "num_comments": story_data.get("descendants", 0),
                            "author": story_data.get("by", "Unknown"),
                            "collected_at": datetime.now().strftime("%Y-%m-%d %H:%M:%S")
                        }
                        collected_stories.append(processed_story)
                        category_count += 1
                        print(f"Got {category_count}/35: {processed_story['title'][:40]}...")

            except requests.exceptions.RequestException as e:
                print(f"Failed to fetch story {story_id}. Moving on. Error: {e}")
                continue

        print(f"Finished {category.upper()}. Sleeping for 2 seconds...")
        time.sleep(2)


    return collected_stories

def save_data(stories):
    if not stories:
        print("No stories collected to save.")
        return

    os.makedirs("data", exist_ok=True)
    date_str = datetime.now().strftime("%Y%m%d")
    filename = f"data/trends_{date_str}.json"

    with open(filename, "w", encoding="utf-8") as json_file:
        json.dump(stories, json_file, indent=4)

    print(f"\nCollected {len(stories)} stories. Saved to {filename}")

# --- THIS IS THE MISSING PIECE ---
# This actually commands Python to run the functions above
if __name__ == "__main__":
    print("Starting TrendPulse Data Collection...")
    final_data = fetch_and_process_stories()
    save_data(final_data)
    print("Script Complete!")

# task2_data_processing
import pandas as pd
import glob
import os

def clean_trend_data():
    # ==========================================
    # TASK 1: Load the JSON File
    # ==========================================

    # Use glob to find all json files in the data folder
    json_files = glob.glob('data/trends_*.json')

    # Safety check: Make sure Task 1 actually created a file
    if not json_files:
        print("Error: No JSON files found in data/. Please run Task 1 first.")
        return

    # Find the most recently modified file (in case you ran Task 1 multiple times)
    latest_file = max(json_files, key=os.path.getctime)

    # Load the JSON into a Pandas DataFrame
    df = pd.read_json(latest_file)
    print(f"Loaded {len(df)} stories from {latest_file}")
    # ==========================================
    # TASK 2: Clean the Data
    # ==========================================

    # 1. Duplicates - keep the first instance, remove any other rows with the same post_id
    df = df.drop_duplicates(subset=['post_id'])
    print(f"After removing duplicates: {len(df)}")

    # 2. Missing values - drop the entire row if post_id, title, or score are missing (NaN)
    df = df.dropna(subset=['post_id', 'title', 'score'])
    print(f"After removing nulls: {len(df)}")

    # 3. Low quality - keep only the rows where the score is 5 or higher
    df = df[df['score'] >= 5]
    print(f"After removing low scores: {len(df)}")

    # 4. Data types - Ensure score and num_comments are whole integers
    # Note: If a story had 0 comments, it might be NaN, so we fill it with 0 first
    df['score'] = df['score'].astype(int)
    df['num_comments'] = df['num_comments'].fillna(0).astype(int)

    # 5. Whitespace - strip accidental spaces from the very beginning or end of the titles
    df['title'] = df['title'].str.strip()

    # ==========================================
    # TASK 3: Save as CSV
    # ==========================================

    # Define the output path
    output_csv = 'data/trends_clean.csv'

    # Save to CSV. index=False prevents Pandas from writing the row numbers into the file
    df.to_csv(output_csv, index=False)
    print(f"Saved {len(df)} rows to {output_csv}")

    # Print the final summary of stories per category
    print("\nStories per category:")

    # value_counts() automatically counts occurrences, to_string() makes it print cleanly
    category_counts = df['category'].value_counts()
    print(category_counts.to_string())

# Run the function
if __name__ == "__main__":
    clean_trend_data()

# task 3 analysis
import pandas as pd
import numpy as np

def analyze_trend_data():
    # ==========================================
    # TASK 1: Load and Explore
    # ==========================================

    # 1. Load the clean CSV into a Pandas DataFrame
    try:
        df = pd.read_csv("data/trends_clean.csv")
    except FileNotFoundError:
        print("Error: data/trends_clean.csv not found. Please run Task 2 first.")
        return

    # 2. Print the shape (rows, columns)
    print(f"Loaded data: {df.shape}")

    # 3. Print the first 5 rows
    print("First 5 rows:")
    print(df.head())

    # 4. Calculate and print average score and comments using Pandas
    avg_score = df['score'].mean()
    avg_comments = df['num_comments'].mean()

    # The :,.0f formats the numbers with commas and 0 decimal places
    print(f"\nAverage score    : {avg_score:,.0f}")
    print(f"Average comments : {avg_comments:,.0f}")

    # ==========================================
    # TASK 2: Basic Analysis with NumPy
    # ==========================================
    print("\n--- NumPy Stats ---")

    # Extract the 'score' column as a pure NumPy array for calculations
    scores_array = df['score'].to_numpy()

    # Use NumPy methods to find the required statistics
    mean_score = np.mean(scores_array)
    median_score = np.median(scores_array)
    std_score = np.std(scores_array)
    max_score = np.max(scores_array)
    min_score = np.min(scores_array)

    print(f"Mean score    : {mean_score:,.0f}")
    print(f"Median score  : {median_score:,.0f}")
    print(f"Std deviation : {std_score:,.0f}")
    print(f"Max score     : {max_score:,.0f}")
    print(f"Min score     : {min_score:,.0f}")

    # Find which category has the most stories
    # value_counts() sorts from highest to lowest automatically.
    # idxmax() grabs the name of the top one, max() grabs the number.
    top_category = df['category'].value_counts().idxmax()
    top_cat_count = df['category'].value_counts().max()
    print(f"Most stories in: {top_category} ({top_cat_count} stories)")

    # Find the story with the most comments
    # idxmax() on a column gives us the row index number of the highest value
    most_comments_index = df['num_comments'].idxmax()
    top_story_title = df.loc[most_comments_index, 'title']
    top_story_comments = df.loc[most_comments_index, 'num_comments']
    print(f'Most commented story: "{top_story_title}" — {top_story_comments:,.0f} comments')

    # ==========================================
    # TASK 3: Add New Columns
    # ==========================================

    # 1. Calculate engagement: num_comments / (score + 1)
    # Pandas applies this formula to every row simultaneously (vectorization)
    df['engagement'] = df['num_comments'] / (df['score'] + 1)

    # 2. Boolean column: True if score is higher than the average, else False
    df['is_popular'] = df['score'] > avg_score

    # ==========================================
    # TASK 4: Save the Result
    # ==========================================

    output_csv = "data/trends_analysed.csv"
    print(f"\nSaved to {output_csv}")

    # Save to a new CSV file, omitting the index column
    df.to_csv(output_csv, index=False)

# Run the script
if __name__ == "__main__":
    analyze_trend_data()