{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyNVwsDe+q3u5bPJVVxYTNZ0",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/chetan9120/trendpulse-chetan/blob/main/task2_data_processing_.py\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "from google.colab import drive\n",
        "drive.mount('/content/drive')"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "g0qh-vzYoSBy",
        "outputId": "34f64764-7dfa-4871-9b3b-89b4f311a98e"
      },
      "execution_count": null,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Mounted at /content/drive\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "os.makedirs(\"data\", exist_ok=True)\n"
      ],
      "metadata": {
        "id": "_m-AmPywoG9j"
      },
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "# task1_data_collection\n",
        "import requests\n",
        "import time\n",
        "import json\n",
        "import os          # to interact with the operating system — such as working with files, directories, environmen\n",
        "import re          # Ex for re:Search the string to see if it starts with \"The\" and ends with \"Spain\"\n",
        "from datetime import datetime\n",
        "\n",
        "# --- Configuration ---\n",
        "TOP_STORIES_URL = \"https://hacker-news.firebaseio.com/v0/topstories.json\"\n",
        "ITEM_URL_TEMPLATE = \"https://hacker-news.firebaseio.com/v0/item/{}.json\"\n",
        "HEADERS = {\"User-Agent\": \"TrendPulse/1.0\"}\n",
        "\n",
        "CATEGORIES = {\n",
        "    \"technology\": [\"ai\", \"software\", \"tech\", \"code\", \"computer\", \"data\", \"cloud\", \"api\", \"gpu\", \"llm\"],\n",
        "    \"worldnews\": [\"war\", \"government\", \"country\", \"president\", \"election\", \"climate\", \"attack\", \"global\"],\n",
        "    \"sports\": [\"nfl\", \"nba\", \"fifa\", \"sport\", \"game\", \"team\", \"player\", \"league\", \"championship\"],\n",
        "    \"science\": [\"research\", \"study\", \"space\", \"physics\", \"biology\", \"discovery\", \"nasa\", \"genome\"],\n",
        "    \"entertainment\": [\"movie\", \"film\", \"music\", \"netflix\", \"game\", \"book\", \"show\", \"award\", \"streaming\"]\n",
        "}\n",
        "\n",
        "def fetch_and_process_stories():\n",
        "    print(\"Fetching top story IDs...\")\n",
        "    try:\n",
        "        response = requests.get(TOP_STORIES_URL, headers=HEADERS)\n",
        "        response.raise_for_status()\n",
        "        story_ids = response.json()\n",
        "    except requests.exceptions.RequestException as e:\n",
        "        print(f\"Failed to fetch top stories: {e}\")\n",
        "        return []\n",
        "\n",
        "    collected_stories = []\n",
        "\n",
        "    for category, keywords in CATEGORIES.items():\n",
        "        print(f\"\\n--- Hunting for 35 stories in: {category.upper()} ---\")\n",
        "        category_count = 0\n",
        "\n",
        "        for story_id in story_ids:\n",
        "            if category_count >= 35:\n",
        "                break\n",
        "\n",
        "            # Skip if we already grabbed this story\n",
        "            if any(s.get(\"post_id\") == story_id for s in collected_stories):\n",
        "                continue\n",
        "\n",
        "            try:\n",
        "                item_url = ITEM_URL_TEMPLATE.format(story_id)\n",
        "                item_response = requests.get(item_url, headers=HEADERS)\n",
        "                item_response.raise_for_status()\n",
        "                story_data = item_response.json()\n",
        "\n",
        "                if story_data and \"title\" in story_data:\n",
        "                    title_lower = story_data[\"title\"].lower()\n",
        "\n",
        "                    match_found = False\n",
        "                    for keyword in keywords:\n",
        "                        if re.search(rf\"\\b{re.escape(keyword)}\\b\", title_lower):\n",
        "                            match_found = True\n",
        "                            break\n",
        "\n",
        "\n",
        "# TASK 2: Extract the Fields\n",
        "                    if match_found:\n",
        "                        processed_story = {\n",
        "                            \"post_id\": story_data.get(\"id\"),\n",
        "                            \"title\": story_data.get(\"title\"),\n",
        "                            \"category\": category,\n",
        "                            \"score\": story_data.get(\"score\", 0),\n",
        "                            \"num_comments\": story_data.get(\"descendants\", 0),\n",
        "                            \"author\": story_data.get(\"by\", \"Unknown\"),\n",
        "                            \"collected_at\": datetime.now().strftime(\"%Y-%m-%d %H:%M:%S\")\n",
        "                        }\n",
        "                        collected_stories.append(processed_story)\n",
        "                        category_count += 1\n",
        "                        print(f\"Got {category_count}/35: {processed_story['title'][:40]}...\")\n",
        "\n",
        "            except requests.exceptions.RequestException as e:\n",
        "                print(f\"Failed to fetch story {story_id}. Moving on. Error: {e}\")\n",
        "                continue\n",
        "\n",
        "        print(f\"Finished {category.upper()}. Sleeping for 2 seconds...\")\n",
        "        time.sleep(2)\n",
        "\n",
        "\n",
        "    return collected_stories\n",
        "\n",
        "def save_data(stories):\n",
        "    if not stories:\n",
        "        print(\"No stories collected to save.\")\n",
        "        return\n",
        "\n",
        "    os.makedirs(\"data\", exist_ok=True)\n",
        "    date_str = datetime.now().strftime(\"%Y%m%d\")\n",
        "    filename = f\"data/trends_{date_str}.json\"\n",
        "\n",
        "    with open(filename, \"w\", encoding=\"utf-8\") as json_file:\n",
        "        json.dump(stories, json_file, indent=4)\n",
        "\n",
        "    print(f\"\\nCollected {len(stories)} stories. Saved to {filename}\")\n",
        "\n",
        "# --- THIS IS THE MISSING PIECE ---\n",
        "# This actually commands Python to run the functions above\n",
        "if __name__ == \"__main__\":\n",
        "    print(\"Starting TrendPulse Data Collection...\")\n",
        "    final_data = fetch_and_process_stories()\n",
        "    save_data(final_data)\n",
        "    print(\"Script Complete!\")"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "obM3B8MZsGd4",
        "outputId": "66939a3a-e009-4bb8-ad7a-cf3cb2b0b30c"
      },
      "execution_count": null,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Starting TrendPulse Data Collection...\n",
            "Fetching top story IDs...\n",
            "\n",
            "--- Hunting for 35 stories in: TECHNOLOGY ---\n",
            "Got 1/35: AI Will Be Met with Violence, and Nothin...\n",
            "Got 2/35: Why AI Sucks at Front End...\n",
            "Got 3/35: How We Broke Top AI Agent Benchmarks: An...\n",
            "Got 4/35: I run multiple $10K MRR companies on a $...\n",
            "Got 5/35: How Complex is my Code?...\n",
            "Got 6/35: Advanced Mac Substitute is an API-level ...\n",
            "Got 7/35: Software Preservation Group: C++ History...\n",
            "Got 8/35: The APL programming language source code...\n",
            "Got 9/35: South Korea introduces universal basic m...\n",
            "Got 10/35: Now is the best time to write code by ha...\n",
            "Got 11/35: France's government is ditching Windows ...\n",
            "Got 12/35: Bild AI (YC W25) Is Hiring a Founding Pr...\n",
            "Got 13/35: The AI Layoff Trap...\n",
            "Got 14/35: AI assistance when contributing to the L...\n",
            "Got 15/35: Launch HN: Twill.ai (YC S25) – Delegate ...\n",
            "Got 16/35: Clojure on Fennel Part One: Persistent D...\n",
            "Got 17/35: France to ditch Windows for Linux to red...\n",
            "Got 18/35: Code is run more than read (2023)...\n",
            "Got 19/35: Lawyer behind AI psychosis cases warns o...\n",
            "Got 20/35: Ask HN: Do you trust AI agents with API ...\n",
            "Got 21/35: Rockstar Games Hacked, Hackers Threaten ...\n",
            "Got 22/35: Git commands I run before reading any co...\n",
            "Got 23/35: How NASA built Artemis II’s fault-tolera...\n",
            "Got 24/35: FBI used iPhone notification data to ret...\n",
            "Got 25/35: Instant 1.0, a backend for AI-coded apps...\n",
            "Got 26/35: The biggest advance in AI since the LLM...\n",
            "Got 27/35: Project Glasswing: Securing critical sof...\n",
            "Got 28/35: Why do we tell ourselves scary stories a...\n",
            "Got 29/35: Show HN: CSS Studio. Design by hand, cod...\n",
            "Got 30/35: An AI robot in my home...\n",
            "Got 31/35: Reallocating $100/Month Claude Code Spen...\n",
            "Got 32/35: C# in Unity 2026: Writing more modern co...\n",
            "Got 33/35: USB for Software Developers: An introduc...\n",
            "Got 34/35: What a legal tech demo does not show...\n",
            "Got 35/35: Show HN: Druids – Build your own softwar...\n",
            "Finished TECHNOLOGY. Sleeping for 2 seconds...\n",
            "\n",
            "--- Hunting for 35 stories in: WORLDNEWS ---\n",
            "Got 1/35: Chimpanzees in Uganda locked in eight-ye...\n",
            "Got 2/35: Polymarket gamblers betting millions on ...\n",
            "Got 3/35: Flashback to a time when government repo...\n",
            "Got 4/35: U.S. Intelligence Shows China Taking a M...\n",
            "Got 5/35: War on Raze...\n",
            "Got 6/35: Mexico's President Sheinbaum Decrees Uni...\n",
            "Got 7/35: Molotov cocktail attack at OpenAI CEO Sa...\n",
            "Got 8/35: Show HN: GovAuctions lets you browse gov...\n",
            "Finished WORLDNEWS. Sleeping for 2 seconds...\n",
            "\n",
            "--- Hunting for 35 stories in: SPORTS ---\n",
            "Got 1/35: Starfling: A one-tap endless orbital sli...\n",
            "Got 2/35: Bevy game development tutorials and in-d...\n",
            "Got 3/35: Team from ETH Zurich make high quality q...\n",
            "Got 4/35: Can It Resolve Doom? Game Engine in 2k D...\n",
            "Got 5/35: Show HN: Moon simulator game, ray-castin...\n",
            "Got 6/35: QB64 Tutorial A beginner's introduction ...\n",
            "Got 7/35: Netflix Prices Went Up Again – I Bought ...\n",
            "Got 8/35: LLM plays an 8-bit Commander X16 game us...\n",
            "Got 9/35: Amazon Luna Will No Longer Allow Owners ...\n",
            "Got 10/35: The team behind a pro-Iran, Lego-themed ...\n",
            "Got 11/35: Breaking the console: a brief history of...\n",
            "Got 12/35: The 1987 game “The Last Ninja” was 40 ki...\n",
            "Got 13/35: Battle for Wesnoth: open-source, turn-ba...\n",
            "Got 14/35: Show HN: Steadcast – Free Mac podcast pl...\n",
            "Got 15/35: Beyond Copy-and-Paste: How Game Studios ...\n",
            "Finished SPORTS. Sleeping for 2 seconds...\n",
            "\n",
            "--- Hunting for 35 stories in: SCIENCE ---\n",
            "Got 1/35: Tell HN: OpenAI silently removed Study M...\n",
            "Got 2/35: Relics of the Heroic Age of Manned Space...\n",
            "Got 3/35: The Bra-and-Girdle Maker That Fashioned ...\n",
            "Got 4/35: Native Instant Space Switching on macOS...\n",
            "Got 5/35: Show HN: Bitcoin and Quantum Computing –...\n",
            "Got 6/35: Research-Driven Agents: When an agent re...\n",
            "Got 7/35: Study found that young adults have grown...\n",
            "Got 8/35: Computational Physics (2nd Edition) (202...\n",
            "Got 9/35: How Close Is Too Close? Applying Fluid D...\n",
            "Got 10/35: Case study: recovery of a corrupted 12 T...\n",
            "Got 11/35: SOM: A minimal Smalltalk for teaching of...\n",
            "Finished SCIENCE. Sleeping for 2 seconds...\n",
            "\n",
            "--- Hunting for 35 stories in: ENTERTAINMENT ---\n",
            "Got 1/35: Show HN: Pardonned.com – A searchable da...\n",
            "Got 2/35: The Life and Death of the Book Review...\n",
            "Got 3/35: The Universal Standard Book Number...\n",
            "Got 4/35: Show HN: FluidCAD – Parametric CAD with ...\n",
            "Got 5/35: Show HN: Waffle – Native macOS terminal ...\n",
            "Got 6/35: Show HN: A WYSIWYG word processor in Pyt...\n",
            "Got 7/35: Show HN: A Better Internet...\n",
            "Got 8/35: Show HN: Eve – Managed OpenClaw for work...\n",
            "Got 9/35: Show HN: Marimo pair – Reactive Python n...\n",
            "Got 10/35: Show HN: I built a Cargo-like build tool...\n",
            "Got 11/35: Show HN: Keeper – embedded secret store ...\n",
            "Got 12/35: Show HN: Brutalist Concrete Laptop Stand...\n",
            "Got 13/35: Show HN: Rust based eBook library for Py...\n",
            "Got 14/35: Show HN: Orange Juice – Small UX improve...\n",
            "Got 15/35: Show HN: I pipe free sports streams into...\n",
            "Got 16/35: Show HN: We built a camera only robot va...\n",
            "Got 17/35: Show HN: Guruka.com – free guided mediat...\n",
            "Got 18/35: Show HN: Unicode Steganography...\n",
            "Got 19/35: Show HN: Go-Bt: Minimalist Behavior Tree...\n",
            "Got 20/35: Show HN: Is Hormuz open yet?...\n",
            "Got 21/35: Show HN: Unlegacy – document everything,...\n",
            "Got 22/35: Show HN: I built a tiny LLM to demystify...\n",
            "Got 23/35: Show HN: Do All the Things...\n",
            "Got 24/35: Show HN: A (marginally) useful x86-64 EL...\n",
            "Got 25/35: Show HN: I built a navigation app that d...\n",
            "Got 26/35: Show HN: TUI-use: Let AI agents control ...\n",
            "Got 27/35: Show HN: An interactive map of Tolkien's...\n",
            "Got 28/35: Show HN: Skrun – Deploy any agent skill ...\n",
            "Got 29/35: Show HN: Ghost Pepper – Local hold-to-ta...\n",
            "Got 30/35: Show HN: Figma for Coding Agents...\n",
            "Got 31/35: Show HN: Real-time AI (audio/video in, v...\n",
            "Got 32/35: Show HN: Gemma Gem – AI model embedded i...\n",
            "Got 33/35: Show HN: Gemma 4 Multimodal Fine-Tuner f...\n",
            "Got 34/35: Show HN: A cartographer's attempt to rea...\n",
            "Got 35/35: Show HN: 41 years sea surface temperatur...\n",
            "Finished ENTERTAINMENT. Sleeping for 2 seconds...\n",
            "\n",
            "Collected 104 stories. Saved to data/trends_20260412.json\n",
            "Script Complete!\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "# task2_data_processing\n",
        "import pandas as pd\n",
        "import glob\n",
        "import os\n",
        "\n",
        "def clean_trend_data():\n",
        "    # ==========================================\n",
        "    # TASK 1: Load the JSON File\n",
        "    # ==========================================\n",
        "\n",
        "    # Use glob to find all json files in the data folder\n",
        "    json_files = glob.glob('data/trends_*.json')\n",
        "\n",
        "    # Safety check: Make sure Task 1 actually created a file\n",
        "    if not json_files:\n",
        "        print(\"Error: No JSON files found in data/. Please run Task 1 first.\")\n",
        "        return\n",
        "\n",
        "    # Find the most recently modified file (in case you ran Task 1 multiple times)\n",
        "    latest_file = max(json_files, key=os.path.getctime)\n",
        "\n",
        "    # Load the JSON into a Pandas DataFrame\n",
        "    df = pd.read_json(latest_file)\n",
        "    print(f\"Loaded {len(df)} stories from {latest_file}\")\n",
        "    # ==========================================\n",
        "    # TASK 2: Clean the Data\n",
        "    # ==========================================\n",
        "\n",
        "    # 1. Duplicates - keep the first instance, remove any other rows with the same post_id\n",
        "    df = df.drop_duplicates(subset=['post_id'])\n",
        "    print(f\"After removing duplicates: {len(df)}\")\n",
        "\n",
        "    # 2. Missing values - drop the entire row if post_id, title, or score are missing (NaN)\n",
        "    df = df.dropna(subset=['post_id', 'title', 'score'])\n",
        "    print(f\"After removing nulls: {len(df)}\")\n",
        "\n",
        "    # 3. Low quality - keep only the rows where the score is 5 or higher\n",
        "    df = df[df['score'] >= 5]\n",
        "    print(f\"After removing low scores: {len(df)}\")\n",
        "\n",
        "    # 4. Data types - Ensure score and num_comments are whole integers\n",
        "    # Note: If a story had 0 comments, it might be NaN, so we fill it with 0 first\n",
        "    df['score'] = df['score'].astype(int)\n",
        "    df['num_comments'] = df['num_comments'].fillna(0).astype(int)\n",
        "\n",
        "    # 5. Whitespace - strip accidental spaces from the very beginning or end of the titles\n",
        "    df['title'] = df['title'].str.strip()\n",
        "\n",
        "    # ==========================================\n",
        "    # TASK 3: Save as CSV\n",
        "    # ==========================================\n",
        "\n",
        "    # Define the output path\n",
        "    output_csv = 'data/trends_clean.csv'\n",
        "\n",
        "    # Save to CSV. index=False prevents Pandas from writing the row numbers into the file\n",
        "    df.to_csv(output_csv, index=False)\n",
        "    print(f\"Saved {len(df)} rows to {output_csv}\")\n",
        "\n",
        "    # Print the final summary of stories per category\n",
        "    print(\"\\nStories per category:\")\n",
        "\n",
        "    # value_counts() automatically counts occurrences, to_string() makes it print cleanly\n",
        "    category_counts = df['category'].value_counts()\n",
        "    print(category_counts.to_string())\n",
        "\n",
        "# Run the function\n",
        "if __name__ == \"__main__\":\n",
        "    clean_trend_data()"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "526MFB8a63Hy",
        "outputId": "f9f62951-0c60-4f9c-89a6-2c97f746e290"
      },
      "execution_count": null,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Loaded 104 stories from data/trends_20260412.json\n",
            "After removing duplicates: 104\n",
            "After removing nulls: 104\n",
            "After removing low scores: 102\n",
            "Saved 102 rows to data/trends_clean.csv\n",
            "\n",
            "Stories per category:\n",
            "category\n",
            "entertainment    35\n",
            "technology       34\n",
            "sports           15\n",
            "science          10\n",
            "worldnews         8\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [],
      "metadata": {
        "id": "6WliFAGW9luA"
      },
      "execution_count": null,
      "outputs": []
    }
  ]
}