# -*- coding: utf-8 -*-
"""task1_data_collection.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10GR_IMDJ4q83zVC2XHGI8RejUVf9gH0z
"""

import requests
import time
import json
import os       # to interact with the operating system — such as working with files, directories, environmen
import re       # Ex for re:Search the string to see if it starts with "The" and ends with "Spain"
from datetime import datetime

# Categories

CATEGORIES = {
    "technology" : ["AI", "software", "tech", "code", "computer", "data", "cloud", "API", "GPU", "LLM"],
    "worldnews"  : ["war", "government", "country", "president", "election", "climate", "attack", "global"],
    "sports"     : ["NFL", "NBA", "FIFA", "sport", "game", "team", "player", "league", "championship"],
    "science"    : ["research", "study", "space", "physics", "biology", "discovery", "NASA", "genome"],
    "entertainment": ["movie", "film", "music", "Netflix", "game", "book", "show", "award", "streaming"]
}

# --- Configuration ---

# step 1
TOP_STORIES_URL = "https://hacker-news.firebaseio.com/v0/topstories.json"

# step 2
ITEM_URL_TEMPLATE = "https://hacker-news.firebaseio.com/v0/item/{}.json"

# step 3
HEADERS = {"User-Agent": "TrendPulse/1.0"}


# task 1
def fetch_and_process_stories():
    print("fetching the top story IDs...")

    try:
        # Use the requests library to fetch the top story IDs, then fetch each story's details
        response = requests.get(TOP_STORIES_URL, headers=HEADERS)
        response.raise_for_status()
        story_ids = response.json()
    except requests.exceptions.RequestException as e:
        # If a request fails, print a message and move on
        print(f"Falied to fetch top stories: {e}")
        return []

    collected_stories = []


    # THE CATEGORY LOOP
    for category_name, keywords in CATEGORIES.items(): # Corrected here
        print(f" searching for 25 in: {category_name.upper()}") # Corrected here
        category_count = 0


        for story_id in story_ids:
                # Once we hit 25 for this specific category, stop checking stories
                if category_count >= 25:
                    break

                # Skip this story if we already collected it in a previous category
                if any(s.get("post_id") == story_id for s in collected_stories):
                    continue

                try:
                    item_url = ITEM_URL_TEMPLATE.format(story_id)
                    item_response = requests.get(item_url, headers=HEADERS)
                    item_response.raise_for_status()
                    story_data = item_response.json()


                    if story_data and "title" in story_data:
                        title_lower = story_data["title"].lower()


                        # Check if THIS specific category's keywords are in the title
                        match_found = False
                        for keyword in keywords: # Keywords now correctly unpacked
                            if re.search(rf"\b{re.escape(keyword)}\b", title_lower):
                                match_found = True
                                break
# TASK 2: Extract the Fields
                        # If it matches, extract the fields and add it to our list
                        if match_found:
                            processed_story = {
                                "post_id": story_data.get("id"),
                                "title": story_data.get("title"),
                                "category": category_name, # Corrected here
                                "score": story_data.get("score", 0),
                                "num_comments": story_data.get("descendants", 0),
                                "author": story_data.get("by", "Unknown"),
                                "collected_at": datetime.now().strftime("%Y-%m-%d %H:%M:%S")
                            }
                            collected_stories.append(processed_story)
                            category_count += 1
                            print(f"Got {category_count}/25: {processed_story['title'][:40]}...")


                except requests.exceptions.RequestException as e:
                    # Rubric Check: "If a request fails, print a message and move on"
                    print(f"Failed to fetch story {story_id}. Moving on. Error: {e}")
                    continue



        # ---------------------------------------------------------
            # THE CATEGORY SLEEP
            # Rubric Check: "Wait 2 seconds between each category...
            # one sleep per category loop, not per individual story fetch"
        # ---------------------------------------------------------
        print(f"Finished {category_name.upper()}. Sleeping for 2 seconds...") # Corrected here
        time.sleep(2)
    return collected_stories

from google.colab import drive
drive.mount('/content/drive')

os.makedirs("data", exist_ok=True)

import requests
import time
import json
import os          # to interact with the operating system — such as working with files, directories, environmen
import re          # Ex for re:Search the string to see if it starts with "The" and ends with "Spain"
from datetime import datetime

# --- Configuration ---
TOP_STORIES_URL = "https://hacker-news.firebaseio.com/v0/topstories.json"
ITEM_URL_TEMPLATE = "https://hacker-news.firebaseio.com/v0/item/{}.json"
HEADERS = {"User-Agent": "TrendPulse/1.0"}

CATEGORIES = {
    "technology": ["ai", "software", "tech", "code", "computer", "data", "cloud", "api", "gpu", "llm"],
    "worldnews": ["war", "government", "country", "president", "election", "climate", "attack", "global"],
    "sports": ["nfl", "nba", "fifa", "sport", "game", "team", "player", "league", "championship"],
    "science": ["research", "study", "space", "physics", "biology", "discovery", "nasa", "genome"],
    "entertainment": ["movie", "film", "music", "netflix", "game", "book", "show", "award", "streaming"]
}

def fetch_and_process_stories():
    print("Fetching top story IDs...")
    try:
        response = requests.get(TOP_STORIES_URL, headers=HEADERS)
        response.raise_for_status()
        story_ids = response.json()
    except requests.exceptions.RequestException as e:
        print(f"Failed to fetch top stories: {e}")
        return []

    collected_stories = []

    for category, keywords in CATEGORIES.items():
        print(f"\n--- Hunting for 35 stories in: {category.upper()} ---")
        category_count = 0

        for story_id in story_ids:
            if category_count >= 35:
                break

            # Skip if we already grabbed this story
            if any(s.get("post_id") == story_id for s in collected_stories):
                continue

            try:
                item_url = ITEM_URL_TEMPLATE.format(story_id)
                item_response = requests.get(item_url, headers=HEADERS)
                item_response.raise_for_status()
                story_data = item_response.json()

                if story_data and "title" in story_data:
                    title_lower = story_data["title"].lower()

                    match_found = False
                    for keyword in keywords:
                        if re.search(rf"\b{re.escape(keyword)}\b", title_lower):
                            match_found = True
                            break


# TASK 2: Extract the Fields
                    if match_found:
                        processed_story = {
                            "post_id": story_data.get("id"),
                            "title": story_data.get("title"),
                            "category": category,
                            "score": story_data.get("score", 0),
                            "num_comments": story_data.get("descendants", 0),
                            "author": story_data.get("by", "Unknown"),
                            "collected_at": datetime.now().strftime("%Y-%m-%d %H:%M:%S")
                        }
                        collected_stories.append(processed_story)
                        category_count += 1
                        print(f"Got {category_count}/35: {processed_story['title'][:40]}...")

            except requests.exceptions.RequestException as e:
                print(f"Failed to fetch story {story_id}. Moving on. Error: {e}")
                continue

        print(f"Finished {category.upper()}. Sleeping for 2 seconds...")
        time.sleep(2)


    return collected_stories

def save_data(stories):
    if not stories:
        print("No stories collected to save.")
        return

    os.makedirs("data", exist_ok=True)
    date_str = datetime.now().strftime("%Y%m%d")
    filename = f"data/trends_{date_str}.json"

    with open(filename, "w", encoding="utf-8") as json_file:
        json.dump(stories, json_file, indent=4)

    print(f"\nCollected {len(stories)} stories. Saved to {filename}")

# --- THIS IS THE MISSING PIECE ---
# This actually commands Python to run the functions above
if __name__ == "__main__":
    print("Starting TrendPulse Data Collection...")
    final_data = fetch_and_process_stories()
    save_data(final_data)
    print("Script Complete!")
